#! /bin/sh
#monitoringsme@outlook.com 
#set -x

# modified march 20th 2020 for FEPOC file tree
nagios=`which nagios`
nagios_cfg=`locate nagios.cfg | grep etc`
if [ -x "$nagios" ] && [ -r "$nagios_cfg" ]; then
# checking permissions on check_icmp
	sudo chown root:root /usr/local/nagios/libexec/check_icmp
	sudo chmod 4755 /usr/local/nagios/libexec/check_icmp
	 sudo 	$nagios -v $nagios_cfg
	else
	echo "You do not have execute permisions on nagios or readable access to the nagios.cfg, you need to run with sudo or be root, you are `id -un`"
fi
