#! /bin/sh
case $1 in
	start)
	transmission-daemon -m -t --password 07740 --username longbranch -a  127.0.0.1,`last | head -1 | awk '{print $3}'`
	;;

	status)
	ps -ef | grep transmission-daemon | grep -v grep  
	;;
	
	stop)
	kill `ps -ef | grep tran | grep -v grep  | awk '{print $2}'`
	if [ echo $? = 0 ]; then 
	echo "Transmission Application Terminated"	
	fi
	;;
	
	*)
	echo "Usage $0 <start stop status>"
	;;

esac
